version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=bridgeaid_dev
      - POSTGRES_USER=bridgeaid
      - POSTGRES_PASSWORD=bridgeaid123
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-0169d=sh6pvu_14zd5b0gejs-8)xqap(5%$o!yh-x*08yo(p82
      - DATABASE_URL=postgres://bridgeaid:bridgeaid123@db:5432/bridgeaid_dev
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
